@AuthService.Api_HostAddress = http://localhost:8081

POST {{AuthService.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user1@cityguide.local",
  "password": "P@ssword123!"
}

###

POST {{AuthService.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user1@cityguide.local",
  "password": "P@ssword123!"
}

###

POST {{AuthService.Api_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "paste-refresh-token"
}

###

POST {{AuthService.Api_HostAddress}}/api/auth/introspect
Content-Type: application/json

{
  "accessToken": "paste-access-token"
}

###
